import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home/Home.module.css'
import Design from '../comps/Home/Design'
import Landing from '../comps/Home/Landing'

export default function Home() {

  /*const cta = document.querySelector(".cta")
        cta.onmousemove = function(e) {
            const x = e.pageX - cta.offsetLeft
            const y = e.pageY - cta.offsetTop

            cta.style.setProperty("--x", x + "px")
            cta.style.setProperty("--y", y + "px")
        }*/

  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Design />
      <Landing />

      <section className={styles.promo}>
        <h1 className={styles.promoTitle}>My Services</h1>
        <section className={styles.articleContainer}>
          <article className={styles.promoArticle}>
            <Image 
              src="/design.svg" 
              alt="illustration about design mockups" 
              width={250} 
              height={200} 
              /*layout="fill"*/ 
            />
            <div>
              <h2 className={styles.promoArticleTitle}>Design</h2>
              <p className={styles.promoArticleText}>Do you need illustrations, logos or ad banners? Maybe a website design with several pages? Name your needs and I create it!</p>
            </div>
          </article>
          <article className={styles.promoArticle}>
            <Image 
              src="/wordpress.svg" 
              alt="illustration about wordpress" 
              width={250} 
              height={200} 
              /*layout="fill"*/ 
            />
            <div>
              <h2 className={styles.promoArticleTitle}>Customization</h2>
              <p className={styles.promoArticleText}>You alredy have a website and you would like to change the design of it to be not just cool but awesome? No proplem, I can handle that! </p>
            </div>
          </article>
          <article className={styles.promoArticle}>
            <Image 
              src="/develop.svg" 
              alt="illustration about design mockups" 
              width={250} 
              height={200} 
              /*layout="fill"*/ 
            />
            <div>
              <h2 className={styles.promoArticleTitle}>Development</h2>
              <p className={styles.promoArticleText}>Need a website from scratch? Is it a portfolio? A blog? Or Company's introductional site? Or you would like to promote / sell something? You just have to come up with a good idea and I will do the rest!</p>
            </div>
          </article>
          <article className={styles.promoArticle}>
            <Image 
              src="/speed.svg" 
              alt="illustration about design mockups" 
              width={250} 
              height={200} 
              /*layout="fill"*/ 
            />
            <div>
              <h2 className={styles.promoArticleTitle}>Performance</h2>
              <p className={styles.promoArticleText}>Did you get some bad reviews about your site because of it's slowliness? I can find and wipe out those nasty problems!</p>
            </div>
          </article>
        </section>
      </section>
    </div>
  )
}
